<?php

declare(strict_types=1);

namespace App\Controllers;

use App\Core\Controller;

/**
 * The pdf.js-based booklet reader. One template (pages/booklet.php) shared by
 * all three booklets, driven entirely by this per-booklet config - including
 * the fully translated UI strings each booklet originally hardcoded.
 */
final class BookletController extends Controller
{
    /** @var array<string, array<string, mixed>> */
    private const BOOKLETS = [
        'aie' => [
            'description' => 'Read "AI For All - The Future Belongs to Us", the AI Unit national booklet explaining artificial intelligence in plain English for every citizen of Mauritius.',
            'lang' => 'en',
            'pageTitle' => "AI For All - English Version · AI Unit, Mauritius",
            'file' => 'documents/Booklet_English.pdf',
            'downloadName' => 'AI-For-All-English.pdf',
            'strings' => [
                'skipLink' => 'Skip to main content',
                'backBtn' => 'Back To Homepage',
                'breadcrumbCategory' => 'AI in Action',
                'breadcrumbTitle' => 'AI For All - English Version',
                'downloadAria' => 'Download the booklet as PDF',
                'downloadLabel' => 'Download PDF',
                'thumbSidebarAria' => 'Page thumbnails',
                'allPages' => 'All Pages',
                'viewerAria' => 'AI For All booklet reader',
                'loadingText' => 'Loading booklet…',
                'loadingHint' => 'If the document does not appear, please ensure',
                'prevPage' => 'Previous page',
                'nextPage' => 'Next page',
                'firstPage' => 'First page',
                'lastPage' => 'Last page',
                'toggleThumbs' => 'Toggle thumbnails',
                'zoomOut' => 'Zoom out',
                'zoomIn' => 'Zoom in',
                'fitScreen' => 'Fit to screen',
                'share' => 'Share',
                'fullscreen' => 'Fullscreen',
                'sharePopupAria' => 'Share options',
                'sharePopupTitle' => 'Share this booklet',
                'copyLink' => 'Copy page link',
                'shareDownload' => 'Download PDF',
                'print' => 'Print',
                'kbdNavigate' => 'Navigate',
                'kbdZoom' => 'Zoom',
                'kbdFullscreen' => 'Fullscreen',
                'kbdFirstPage' => 'First page',
                'kbdLastPage' => 'Last page',
                'errorTitle' => 'Unable to load booklet',
                'errorHint' => 'Please ensure',
                'errorHint2' => 'is present and accessible on the server.',
                'errorDownloadHint' => 'You can also use the Download PDF button above.',
                'linkCopied' => 'Link copied to clipboard!',
                'linkCopyFailed' => 'Could not copy link.',
                'textViewLabel' => 'View as text',
                'textViewHeading' => 'Text version of this booklet',
                'textViewInstructions' => 'Screen reader help: Press Down Arrow to read line by line, or NVDA+Down Arrow to read continuously. Tab moves only between buttons and links.',
                'textViewLoading' => 'Extracting text from the booklet…',
                'textViewReadyLoading' => 'Text version ready. Loading the remaining pages…',
                'textViewReady' => 'All text pages are ready.',
                'textViewPartialError' => 'Some pages could not be converted to text.',
                'textViewError' => 'Sorry, the text could not be extracted from this booklet. Please use the Download PDF button instead.',
                'textViewPageEmpty' => 'No extractable text on this page - it may be an image.',
                'pageHeadingPrefix' => 'Page',
            ],
        ],
        'aim' => [
            'description' => 'Lir "AI Pou Nou Tou - Lavenir Apartenir A Nou Tou", livre nasional Linite LIA ki explik lintelizans artifisiel an Kreol Morisien pou tou sitwayen.',
            'lang' => 'mfe',
            'pageTitle' => "AI Pou Nou Tou - Version Kreol · Linite L'IA, Moris",
            'file' => 'documents/Booklet_Kreol.pdf',
            'downloadName' => 'AI-Pou-Nou-Tou-Kreol.pdf',
            'strings' => [
                'skipLink' => 'Ale direkteman lor kontenu',
                'backBtn' => 'Retourne',
                'breadcrumbCategory' => "L'IA an Aksyon",
                'breadcrumbTitle' => 'AI Pou Nou Tou - Version Kreol',
                'downloadAria' => 'Telecharge livret la koumm PDF',
                'downloadLabel' => 'Telecharge PDF',
                'thumbSidebarAria' => 'Miniature bann paz',
                'allPages' => 'Tou bann paz',
                'viewerAria' => 'Lecter livret AI Pou Nou Tou',
                'loadingText' => 'Livret pe charge…',
                'loadingHint' => 'Si dokiman pa afiche, asire ou ki',
                'prevPage' => 'Paz avan',
                'nextPage' => 'Paz apre',
                'firstPage' => 'Premye paz',
                'lastPage' => 'Dernie paz',
                'toggleThumbs' => 'Montre / kasiet miniature',
                'zoomOut' => 'Zoom aryer',
                'zoomIn' => 'Zoom avan',
                'fitScreen' => 'Adapte a lekran',
                'share' => 'Partaz',
                'fullscreen' => 'Plen lekran',
                'sharePopupAria' => 'Opsyon partaz',
                'sharePopupTitle' => 'Partaz livret la',
                'copyLink' => 'Kopye lyen paz la',
                'shareDownload' => 'Telecharge PDF',
                'print' => 'Imprime',
                'kbdNavigate' => 'Navige',
                'kbdZoom' => 'Zoom',
                'kbdFullscreen' => 'Plen lekran',
                'kbdFirstPage' => 'Premye paz',
                'kbdLastPage' => 'Dernie paz',
                'errorTitle' => 'Nou pa kapav sarz livret la',
                'errorHint' => 'Asire ou ki fichier',
                'errorHint2' => 'disponib lor server.',
                'errorDownloadHint' => 'Ou kapav itiliz bouton Telecharge PDF anlerla.',
                'linkCopied' => 'Lyen kopye!',
                'linkCopyFailed' => 'Nou pa finn arrive kopye lyen la.',
                'textViewLabel' => 'Montre an tex',
                'textViewHeading' => 'Vesion an tex sa livret la',
                'textViewInstructions' => 'Led pou lekter ekran: Apiy fless anba pou lir lalign par lalign, ouswa NVDA+fless anba pou lir san arete. Tab deplas zis ant bann bouton ek lien.',
                'textViewLoading' => 'Pe ekstrait tex livret la…',
                'textViewReadyLoading' => 'Vesion an tex pare. Pe sarz bann lezot paz…',
                'textViewReady' => 'Tou bann paz an tex pare.',
                'textViewPartialError' => 'Sertin paz pa finn kapav konverti an tex.',
                'textViewError' => 'Nou pa finn arrive ekstrait tex livret la. Servi bouton Telecharge PDF.',
                'textViewPageEmpty' => 'Pena tex ki kapav ekstrait lor paz sa la - kitfwa li enn zimaz.',
                'pageHeadingPrefix' => 'Paz',
            ],
        ],
        'livret' => [
            'description' => 'Read the educational booklet on digital violence against children: how to recognise it, how to prevent it, and where to find help in Mauritius.',
            'lang' => 'fr',
            'pageTitle' => 'Violence Numérique Contre Les Enfants - Livret Pédagogique',
            'file' => 'documents/violence.pdf',
            'downloadName' => 'Livret-Violence-Numerique.pdf',
            'strings' => [
                'skipLink' => 'Aller au contenu principal',
                'backBtn' => 'Back To Homepage',
                'breadcrumbCategory' => 'AI in Action',
                'breadcrumbTitle' => 'Violence Numérique Contre Les Enfants',
                'downloadAria' => 'Télécharger le livret en PDF',
                'downloadLabel' => 'Télécharger PDF',
                'thumbSidebarAria' => 'Miniatures des pages',
                'allPages' => 'Toutes les pages',
                'viewerAria' => 'Lecteur du livret pédagogique',
                'loadingText' => 'Chargement du livret en cours…',
                'loadingHint' => "Si le document ne s'affiche pas, vérifiez que",
                'prevPage' => 'Page précédente',
                'nextPage' => 'Page suivante',
                'firstPage' => 'Première page',
                'lastPage' => 'Dernière page',
                'toggleThumbs' => 'Afficher / masquer les miniatures',
                'zoomOut' => 'Zoom arrière',
                'zoomIn' => 'Zoom avant',
                'fitScreen' => "Ajuster à l'écran",
                'share' => 'Partager',
                'fullscreen' => 'Plein écran',
                'sharePopupAria' => 'Options de partage',
                'sharePopupTitle' => 'Partager ce livret',
                'copyLink' => 'Copier le lien de la page',
                'shareDownload' => 'Télécharger PDF',
                'print' => 'Imprimer',
                'kbdNavigate' => 'Naviguer',
                'kbdZoom' => 'Zoom',
                'kbdFullscreen' => 'Plein écran',
                'kbdFirstPage' => '1ère page',
                'kbdLastPage' => 'Dernière page',
                'errorTitle' => 'Impossible de charger le livret',
                'errorHint' => 'Assurez-vous que le fichier',
                'errorHint2' => 'est bien présent sur le serveur.',
                'errorDownloadHint' => 'Vous pouvez aussi utiliser le bouton Télécharger PDF ci-dessus.',
                'linkCopied' => 'Lien copié dans le presse-papiers !',
                'linkCopyFailed' => 'Impossible de copier le lien.',
                'textViewLabel' => 'Voir en texte',
                'textViewHeading' => 'Version texte de ce livret',
                'textViewInstructions' => 'Aide au lecteur d’écran : appuyez sur Flèche bas pour lire ligne par ligne, ou sur NVDA+Flèche bas pour lire en continu. Tabulation ne déplace le focus qu’entre les boutons et les liens.',
                'textViewLoading' => 'Extraction du texte du livret…',
                'textViewReadyLoading' => 'Version texte prête. Chargement des pages restantes…',
                'textViewReady' => 'Toutes les pages de texte sont prêtes.',
                'textViewPartialError' => 'Certaines pages n’ont pas pu être converties en texte.',
                'textViewError' => "Désolé, le texte n'a pas pu être extrait de ce livret. Veuillez utiliser le bouton Télécharger PDF.",
                'textViewPageEmpty' => 'Aucun texte extractible sur cette page - il peut s\'agir d\'une image.',
                'pageHeadingPrefix' => 'Page',
            ],
        ],
    ];

    public function show(string $slug): void
    {
        $booklet = self::BOOKLETS[$slug] ?? null;

        if ($booklet === null) {
            $this->notFound();

            return;
        }

        $this->view('booklet', [
            'title' => $booklet['pageTitle'],
            'description' => $booklet['description'],
            'ogType' => 'article',
            'lang' => $booklet['lang'],
            'pdfUrl' => asset($booklet['file']),
            'downloadName' => $booklet['downloadName'],
            's' => $booklet['strings'],
        ], null);
    }
}
